config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :discussions

  root to: "discussions#index"

  get "/auth/:provider/callback" => "sessions#new"
  get "/auth/sign-out" => "sessions#sign_out", as: :sign_out
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user
end

app/models/photo.rb
class Photo < ApplicationRecord
  attachment :image, type: :image
end

app/models/user.rb
class User < ApplicationRecord
  has_many :discussions

  def self.create_or_update_from(auth_info)
    user = where(uid: auth_info[:uid], provider: auth_info[:provider]).first_or_create
    user.update(
      nickname: auth_info[:info][:nickname],
      name: auth_info[:info][:name],
      email: auth_info[:info][:email],
      location: auth_info[:info][:location],
      image_url: auth_info[:info][:image],
      description: auth_info[:info][:description],
      token: auth_info[:credentials][:token],
      secret: auth_info[:credentials][:secret],
    )
    user
  end

  def owns_discussion?(discussion)
    # discussions.include?(discussion)
    self.id == discussion.user_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  helper_method :current_user
  helper_method :user_logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def user_logged_in?
    current_user.present?
  end

  def authenticate_user!
    unless user_logged_in?
      flash[:notice] = "You need to login."
      redirect_to root_path
    end
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_own_discussion, only: [:edit, :update, :destroy]

  # GET /discussions
  # GET /discussions.json
  def index
    @discussions = Discussion.all
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show
    @discussion = Discussion.find(params[:id])
  end

  # GET /discussions/new
  def new
    @discussion = Discussion.new
  end

  # GET /discussions/1/edit
  def edit
  end

  # POST /discussions
  # POST /discussions.json
  def create
    @discussion = current_user.discussions.new(discussion_params)

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: "Discussion was successfully created." }
        format.json { render :show, status: :created, location: @discussion }
      else
        format.html { render :new }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discussions/1
  # PATCH/PUT /discussions/1.json
  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        format.html { redirect_to @discussion, notice: "Discussion was successfully updated." }
        format.json { render :show, status: :ok, location: @discussion }
      else
        format.html { render :edit }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
    @discussion.destroy
    respond_to do |format|
      format.html { redirect_to discussions_url, notice: "Discussion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_own_discussion
    begin
      @discussion = current_user.discussions.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      logger.info "===================================="
      logger.info e
      logger.info "===================================="
      flash[:notice] = "You don't have access to that."
      redirect_to root_path
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def discussion_params
    params.require(:discussion).permit(:headline, :content)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: "Photo was successfully created." }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: "Photo was successfully updated." }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: "Photo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_photo
    @photo = Photo.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def photo_params
    params.require(:photo).permit(:name, :image, :remove_image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new]

  def new
    user = User.create_or_update_from(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def sign_out
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/discussions/_form.html.erb
<%= form_with(model: discussion, local: true) do |form| %>
  <% if discussion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discussion.errors.count, "error") %> prohibited this discussion from being saved:</h2>

      <ul>
      <% discussion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :headline %>
    <%= form.text_field :headline %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit "Save Discussion", class:"waves-effect waves-light btn" %>
  </div>
  <br>
<% end %>

app/views/discussions/edit.html.erb
<h1>Editing Discussion</h1>

<%= render 'form', discussion: @discussion %>

<%= link_to 'Show', @discussion %> |
<%= link_to 'Back', discussions_path %>

app/views/discussions/index.html.erb
<p id="notice"><%= notice %></p>

<h4>Discussions</h4>

<table>
  <thead>
    <tr>
      <th>Headline</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @discussions.each do |discussion| %>
      <tr>
        <td><%= discussion.headline %></td>
        <td><%= discussion.content %></td>
        <td><%= link_to 'Show', discussion %></td>
        
        <% if user_logged_in? and current_user.owns_discussion?(discussion) %>
          <td><%= link_to 'Edit', edit_discussion_path(discussion) %></td>
          <td><%= link_to 'Delete', discussion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if user_logged_in? %>
  <br>
  <%= link_to 'New Discussion', new_discussion_path, class: "waves-effect waves-light btn" %>
<% end %>

app/views/discussions/new.html.erb
<h4>New Discussion</h4>

<%= render 'form', discussion: @discussion %>

<%= link_to 'Back', discussions_path, class: "waves-effect waves-light btn" %>

app/views/discussions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Headline:</strong>
  <%= @discussion.headline %>
</p>

<p>
  <strong>Content:</strong>
  <%= @discussion.content %>
</p>

<%= link_to 'Edit', edit_discussion_path(@discussion) %> |
<%= link_to 'Back', discussions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LetsReef</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar-fixed">
      <nav class="light-blue darken-2">
        <div class="nav-wrapper">
          <div class="container">
            <%= link_to "ImReefer", root_path, class: "brand-logo"  %>
            <ul class="right hide-on-med-and-down">
              <% if user_logged_in? %>
                <%= image_tag(current_user.image_url, width: 50, height: 50)  %>
                <li><%= link_to "Sign out", sign_out_path %></li>
              <% else %>
                <li><a href="/auth/twitter">Sign in with Twitter</a></li>
              <% end%>
            </ul>
          </div>
        </div>
      </nav>
    </div>

  <div class="container">

    

    <%= yield %>
  </div>
    
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

   <div class="field">
    <%= form.attachment_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photos</h1>

<div>
  <% @photos.each do |photo| %>       
    <%= link_to(image_tag(attachment_url(photo, :image, :fit, 100, 100, format: 'jpg')), attachment_url(photo, :image, :fit, 500, 500, format: 'jpg'), data: { lightbox: "example-set", title: photo.name }) %>     
  <% end %>
</div>    

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @photo.name %>

  <div>
  <% if @photo.image_id? %>
  <%= image_tag attachment_url(@photo, :image) %>
<% end %>
</div>    
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>